/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/AGV.glb -t -r public -o src/components/AGV.tsx 
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
    nodes: {
        ['25A2001-01-1_-_Part']: THREE.Mesh
        ['25A2001-01-1_-_Part_2']: THREE.Mesh
        ['25A2001-02-1_-_Part']: THREE.Mesh
        ['25A2001-02-2_-_Part']: THREE.Mesh
        ['25A2001-03-1_-_Part']: THREE.Mesh
        ['25A2001-03-1_-_Part_2']: THREE.Mesh
        ['25A2002-01-1_-_Part']: THREE.Mesh
        ['25A2002-01-2_-_Part']: THREE.Mesh
        ['25A2002-02-1_-_Part']: THREE.Mesh
        ['25A2002-03-1_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-5_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-6_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-7_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-8_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-9_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-11_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-10_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-22_-_Part']: THREE.Mesh
        ['25A2002-03-2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-12_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-16_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-17_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-19_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-20_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-21_-_Part']: THREE.Mesh
        ['25A3001-03-1_-_Part']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_2']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_3']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_4']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_5']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_6']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_7']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_8']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_9']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_10']: THREE.Mesh
        ['PG457_DC_Motor-2_-_Part_11']: THREE.Mesh
        ['25A2002-04-1_-_Part']: THREE.Mesh
        ['25A3001-05-1_-_Part']: THREE.Mesh
        ['25A3001-05-1_-_Part_2']: THREE.Mesh
        ['25A2002-05-1_-_Part']: THREE.Mesh
        ['25A2002-06-1_-_Part']: THREE.Mesh
        ['25A2002-06-2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_-_Part']: THREE.Mesh
        ['M4_Split_Washer-2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-3_-_Part']: THREE.Mesh
        ['M4_Split_Washer-5_-_Part']: THREE.Mesh
        ['M4_Split_Washer-6_-_Part']: THREE.Mesh
        ['M4_Split_Washer-8_-_Part']: THREE.Mesh
        ['M4_Split_Washer-9_-_Part']: THREE.Mesh
        ['M4_Split_Washer-10_-_Part']: THREE.Mesh
        ['M4_Split_Washer-11_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-2_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-3_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-4_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-5_-_Part']: THREE.Mesh
        ['Revolve1_-_Part']: THREE.Mesh
        ['Combine1_-_Part']: THREE.Mesh
        ['Revolve1_2_-_Part']: THREE.Mesh
        ['Combine1_2_-_Part']: THREE.Mesh
        ['Revolve1_3_-_Part']: THREE.Mesh
        ['Combine1_3_-_Part']: THREE.Mesh
        ['Revolve1_4_-_Part']: THREE.Mesh
        ['Combine1_4_-_Part']: THREE.Mesh
        ['M5_Split_Washer-2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-3_-_Part']: THREE.Mesh
        ['M5_Split_Washer-4_-_Part']: THREE.Mesh
        ['M5_Split_Washer-5_-_Part']: THREE.Mesh
        ['M5_Split_Washer-6_-_Part']: THREE.Mesh
        ['M5_Split_Washer-7_-_Part']: THREE.Mesh
        ['M5_Split_Washer-8_-_Part']: THREE.Mesh
        ['M5_Split_Washer-9_-_Part']: THREE.Mesh
        ['M5_Split_Washer-10_-_Part']: THREE.Mesh
        ['M5_Split_Washer-11_-_Part']: THREE.Mesh
        ['M5_Split_Washer-12_-_Part']: THREE.Mesh
        ['M5_Split_Washer-13_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-3_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-4_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-5_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-6_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-7_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-8_-_Part']: THREE.Mesh
        ['Revolve1_5_-_Part']: THREE.Mesh
        ['Combine1_5_-_Part']: THREE.Mesh
        ['Revolve1_6_-_Part']: THREE.Mesh
        ['Combine1_6_-_Part']: THREE.Mesh
        ['Revolve1_7_-_Part']: THREE.Mesh
        ['Combine1_7_-_Part']: THREE.Mesh
        ['Revolve1_8_-_Part']: THREE.Mesh
        ['Combine1_8_-_Part']: THREE.Mesh
        ['Revolve1_9_-_Part']: THREE.Mesh
        ['Combine1_9_-_Part']: THREE.Mesh
        ['Revolve1_10_-_Part']: THREE.Mesh
        ['Combine1_10_-_Part']: THREE.Mesh
        ['4X6_Grub_Screw-1_-_Part']: THREE.Mesh
        ['4X6_Grub_Screw-2_-_Part']: THREE.Mesh
        ['25A2004-01-2_-_Part']: THREE.Mesh
        ['25A2004-02-1_-_Part']: THREE.Mesh
        ['25A2004-02-5_-_Part']: THREE.Mesh
        ['25A2004-02-6_-_Part']: THREE.Mesh
        ['25A2004-02-4_-_Part']: THREE.Mesh
        ['25A2004-01-2_2_-_Part']: THREE.Mesh
        ['25A2004-02-1_2_-_Part']: THREE.Mesh
        ['25A2004-02-5_2_-_Part']: THREE.Mesh
        ['25A2004-02-6_2_-_Part']: THREE.Mesh
        ['25A2004-02-4_2_-_Part']: THREE.Mesh
        ['25A2005-01-1_-_Part']: THREE.Mesh
        ['25A2004-02-1_3_-_Part']: THREE.Mesh
        ['25A2004-02-2_-_Part']: THREE.Mesh
        ['25A2004-02-3_-_Part']: THREE.Mesh
        ['25A2004-02-4_3_-_Part']: THREE.Mesh
        ['25A2005-01-1_2_-_Part']: THREE.Mesh
        ['25A2004-02-1_4_-_Part']: THREE.Mesh
        ['25A2004-02-2_2_-_Part']: THREE.Mesh
        ['25A2004-02-3_2_-_Part']: THREE.Mesh
        ['25A2004-02-4_4_-_Part']: THREE.Mesh
        ['25A2006-01-1_-_Part']: THREE.Mesh
        ['25A3005-02-1_-_Part']: THREE.Mesh
        ['25A2001-07-1_-_Part']: THREE.Mesh
        ['25A1008-01-1_-_Part']: THREE.Mesh
        ['25A1008-02-1_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-1_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_2_-_Part']: THREE.Mesh
        ['25A1008-02-2_-_Part']: THREE.Mesh
        ['25A1008-02-3_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-3_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_2_-_Part']: THREE.Mesh
        ['25A1008-02-4_-_Part']: THREE.Mesh
        ['25A1008-02-5_-_Part']: THREE.Mesh
        ['25A1008-02-6_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-4_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-5_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-6_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-5_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_2_-_Part']: THREE.Mesh
        ['FRONT_LED-1_-_Part']: THREE.Mesh
        ['FRONT_LED-1_-_Part_2']: THREE.Mesh
        ['FRONT_LED-1_-_Part_3']: THREE.Mesh
        ['LEFT_RIGHT_LED-1_-_Part']: THREE.Mesh
        ['LEFT_RIGHT_LED-1_-_Part_2']: THREE.Mesh
        ['LEFT_RIGHT_LED-1_-_Part_3']: THREE.Mesh
        ['RIGHT_LED-1_-_Part']: THREE.Mesh
        ['RIGHT_LED-1_-_Part_2']: THREE.Mesh
        ['RIGHT_LED-1_-_Part_3']: THREE.Mesh
        ['LED_Elbow-1-1_-_Part']: THREE.Mesh
        ['LED_Elbow-1-2_-_Part']: THREE.Mesh
        ['25A2002-01-1_2_-_Part']: THREE.Mesh
        ['25A2002-01-2_2_-_Part']: THREE.Mesh
        ['25A2002-02-1_2_-_Part']: THREE.Mesh
        ['25A2002-03-1_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-5_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-6_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-7_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-8_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-9_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-11_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-10_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-22_2_-_Part']: THREE.Mesh
        ['25A2002-03-2_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-12_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-16_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-17_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-19_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-20_2_-_Part']: THREE.Mesh
        ['4X12_18-8_Stainless_Steel_Socket_Head_Screws-21_2_-_Part']: THREE.Mesh
        ['25A3001-03-1_2_-_Part']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_2']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_3']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_4']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_5']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_6']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_7']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_8']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_9']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_10']: THREE.Mesh
        ['PG457_DC_Motor-2_2_-_Part_11']: THREE.Mesh
        ['25A2002-04-1_2_-_Part']: THREE.Mesh
        ['25A3001-05-1_2_-_Part']: THREE.Mesh
        ['25A3001-05-1_2_-_Part_2']: THREE.Mesh
        ['25A2002-05-1_2_-_Part']: THREE.Mesh
        ['25A2002-06-1_2_-_Part']: THREE.Mesh
        ['25A2002-06-2_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_3_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_3_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_3_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_3_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_3_-_Part']: THREE.Mesh
        ['M4_Split_Washer-2_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-3_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-5_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-6_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-8_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-9_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-10_2_-_Part']: THREE.Mesh
        ['M4_Split_Washer-11_2_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-2_2_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-3_2_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-4_2_-_Part']: THREE.Mesh
        ['4X30_Button_Head_Hex_Drive_Screw-5_2_-_Part']: THREE.Mesh
        ['Revolve1_11_-_Part']: THREE.Mesh
        ['Combine1_11_-_Part']: THREE.Mesh
        ['Revolve1_12_-_Part']: THREE.Mesh
        ['Combine1_12_-_Part']: THREE.Mesh
        ['Revolve1_13_-_Part']: THREE.Mesh
        ['Combine1_13_-_Part']: THREE.Mesh
        ['Revolve1_14_-_Part']: THREE.Mesh
        ['Combine1_14_-_Part']: THREE.Mesh
        ['M5_Split_Washer-2_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-3_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-4_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-5_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-6_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-7_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-8_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-9_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-10_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-11_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-12_2_-_Part']: THREE.Mesh
        ['M5_Split_Washer-13_2_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-3_2_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-4_2_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-5_2_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-6_2_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-7_2_-_Part']: THREE.Mesh
        ['5X20_Button_Head_Hex_Drive_Screw-8_2_-_Part']: THREE.Mesh
        ['Revolve1_15_-_Part']: THREE.Mesh
        ['Combine1_15_-_Part']: THREE.Mesh
        ['Revolve1_16_-_Part']: THREE.Mesh
        ['Combine1_16_-_Part']: THREE.Mesh
        ['Revolve1_17_-_Part']: THREE.Mesh
        ['Combine1_17_-_Part']: THREE.Mesh
        ['Revolve1_18_-_Part']: THREE.Mesh
        ['Combine1_18_-_Part']: THREE.Mesh
        ['Revolve1_19_-_Part']: THREE.Mesh
        ['Combine1_19_-_Part']: THREE.Mesh
        ['Revolve1_20_-_Part']: THREE.Mesh
        ['Combine1_20_-_Part']: THREE.Mesh
        ['4X6_Grub_Screw-1_2_-_Part']: THREE.Mesh
        ['4X6_Grub_Screw-2_2_-_Part']: THREE.Mesh
        ['25A1008-01-1_2_-_Part']: THREE.Mesh
        ['25A1008-02-1_2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-1_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_4_-_Part']: THREE.Mesh
        ['25A1008-02-2_2_-_Part']: THREE.Mesh
        ['25A1008-02-3_2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-2_2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-3_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_4_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_4_-_Part']: THREE.Mesh
        ['25A1008-02-4_2_-_Part']: THREE.Mesh
        ['25A1008-02-5_2_-_Part']: THREE.Mesh
        ['25A1008-02-6_2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-4_2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-5_2_-_Part']: THREE.Mesh
        ['M4_T_slot_nut_-_2020-6_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_4_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-5_2_-_Part']: THREE.Mesh
        ['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_4_-_Part']: THREE.Mesh
        ['Default_-_Part']: THREE.Mesh
        ['Default_-_Part_clonedChild']: THREE.Mesh
    }
    materials: {
        ['black high gloss plastic']: THREE.MeshStandardMaterial
        ['agv blue polished abs plastic']: THREE.MeshStandardMaterial
        ['black spray paint']: THREE.MeshPhysicalMaterial
        ['agv blue polished abs plastic-2']: THREE.MeshStandardMaterial
        ['polished steel']: THREE.MeshStandardMaterial
        color: THREE.MeshStandardMaterial
        ['color-2']: THREE.MeshStandardMaterial
        ['matte silver']: THREE.MeshStandardMaterial
        ['white high gloss plastic']: THREE.MeshStandardMaterial
        ['white high gloss plastic-2']: THREE.MeshStandardMaterial
        ['brushed aluminum']: THREE.MeshStandardMaterial
        ['chromium plate']: THREE.MeshStandardMaterial
        ['white high gloss plastic-3']: THREE.MeshStandardMaterial
        ['white high gloss plastic-4']: THREE.MeshStandardMaterial
        ['white high gloss plastic-5']: THREE.MeshStandardMaterial
        ['white high gloss plastic-6']: THREE.MeshStandardMaterial
        ['matte steel']: THREE.MeshStandardMaterial
        ['black spray paint-2']: THREE.MeshPhysicalMaterial
        ['black spray paint-3']: THREE.MeshPhysicalMaterial
        ['black medium gloss plastic']: THREE.MeshStandardMaterial
        ['color-9']: THREE.MeshStandardMaterial
        ['white led']: THREE.MeshStandardMaterial
        ['red led']: THREE.MeshStandardMaterial
        ['factory floor']: THREE.MeshStandardMaterial
    }
    animations: any[]
}

export function AGV(props: any) {
    const { nodes, materials } = useGLTF('/AGV.glb') as unknown as GLTFResult
    const group = useRef<THREE.Group>(null)
    const innerGroup = useRef<THREE.Group>(null)

    // State to manage hover effects
    const [hovered, setHovered] = useState(false)

    // Smooth floating animation and highly reactive mouse tracking
    useFrame((state) => {
        if (!innerGroup.current) return;
        const t = state.clock.getElapsedTime();
        const mouseX = state.pointer.x;
        const mouseY = state.pointer.y;

        // Strictly bounded positional movement to prevent clipping (stays within a very tight radius)
        const targetPosX = mouseX * 0.15;
        const targetPosY = (Math.sin(t * 2) * 0.05) + (mouseY * 0.1);

        // Reactive rotation looking towards the mouse, also restrained
        const targetRotY = mouseX * (Math.PI / 6);
        const targetRotX = -mouseY * (Math.PI / 12);

        // Apply smooth interpolation mapping mouse coords to 3D position
        innerGroup.current.position.x = THREE.MathUtils.lerp(innerGroup.current.position.x, targetPosX, 0.05);
        innerGroup.current.position.y = THREE.MathUtils.lerp(innerGroup.current.position.y, targetPosY, 0.05);

        // Apply smooth rotation interpolation
        innerGroup.current.rotation.x = THREE.MathUtils.lerp(innerGroup.current.rotation.x, targetRotX, 0.08);
        innerGroup.current.rotation.y = THREE.MathUtils.lerp(innerGroup.current.rotation.y, targetRotY, 0.08);

        // Scale up slightly when hovered
        const targetScale = hovered ? 1.05 : 1;
        innerGroup.current.scale.setScalar(THREE.MathUtils.lerp(innerGroup.current.scale.x, targetScale, 0.1));
    });

    const handlePointerOver = () => {
        document.body.style.cursor = 'pointer';
        setHovered(true);
    };

    const handlePointerOut = () => {
        document.body.style.cursor = 'auto';
        setHovered(false);
    };

    const handleClick = (e: any) => {
        e.stopPropagation();
        // Scroll to the programs section when clicked
        const programsSection = document.getElementById('programs');
        if (programsSection) {
            programsSection.scrollIntoView({ behavior: 'smooth' });
        }
    };

    return (
        <group
            ref={group}
            {...props}
            dispose={null}
            onPointerOver={handlePointerOver}
            onPointerOut={handlePointerOut}
            onClick={handleClick}
            rotation={[Math.PI / 8, -Math.PI / 4, 0]} // Give it a nice isometric starting angle
        >
            <group ref={innerGroup}>
                <group position={[0, 0.043, 0]}>
                    <group position={[0.37, 0, 0]}>
                        <mesh geometry={nodes['25A2001-03-1_-_Part'].geometry} material={materials['agv blue polished abs plastic-2']} />
                        <mesh geometry={nodes['25A2001-03-1_-_Part_2'].geometry} material={materials['black high gloss plastic']} />
                    </group>
                    <group position={[-0.368, 0.13, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                        <mesh geometry={nodes['FRONT_LED-1_-_Part'].geometry} material={materials['color-2']} />
                        <mesh geometry={nodes['FRONT_LED-1_-_Part_2'].geometry} material={materials['white led']} />
                        <mesh geometry={nodes['FRONT_LED-1_-_Part_3'].geometry} material={materials['red led']} />
                    </group>
                    <group position={[-0.324, 0.13, 0.218]} rotation={[-Math.PI / 2, 0, -2.356]}>
                        <mesh geometry={nodes['LEFT_RIGHT_LED-1_-_Part'].geometry} material={materials['white led']} />
                        <mesh geometry={nodes['LEFT_RIGHT_LED-1_-_Part_2'].geometry} material={materials['red led']} />
                        <mesh geometry={nodes['LEFT_RIGHT_LED-1_-_Part_3'].geometry} material={materials['color-2']} />
                    </group>
                    <group position={[-0.324, 0.13, -0.217]} rotation={[-Math.PI / 2, 0, 2.356]}>
                        <mesh geometry={nodes['RIGHT_LED-1_-_Part'].geometry} material={materials['white led']} />
                        <mesh geometry={nodes['RIGHT_LED-1_-_Part_2'].geometry} material={materials['color-2']} />
                        <mesh geometry={nodes['RIGHT_LED-1_-_Part_3'].geometry} material={materials['red led']} />
                    </group>

                    <mesh geometry={nodes['25A2001-01-1_-_Part'].geometry} material={materials['black high gloss plastic']} />
                    <mesh geometry={nodes['25A2001-01-1_-_Part_2'].geometry} material={materials['agv blue polished abs plastic']} />
                    <mesh geometry={nodes['25A2001-02-1_-_Part'].geometry} material={materials['black spray paint']} position={[-0.332, 0.057, 0.225]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} />
                    <mesh geometry={nodes['25A2001-02-2_-_Part'].geometry} material={materials['black spray paint']} position={[-0.332, 0.057, -0.225]} rotation={[-Math.PI / 2, 0, -2.356]} />
                    <group position={[0.032, -0.005, -0.151]} rotation={[0, 0, -0.663]}>
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part'].geometry} material={materials['matte silver']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_2'].geometry} material={materials['white high gloss plastic']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_3'].geometry} material={materials['white high gloss plastic-2']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_4'].geometry} material={materials['matte silver']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_5'].geometry} material={materials['brushed aluminum']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_6'].geometry} material={materials['chromium plate']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_7'].geometry} material={materials['white high gloss plastic-3']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_8'].geometry} material={materials['white high gloss plastic-4']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_9'].geometry} material={materials['white high gloss plastic-5']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_10'].geometry} material={materials['chromium plate']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_-_Part_11'].geometry} material={materials['white high gloss plastic-6']} />
                    </group>
                    <group position={[0.016, 0.027, -0.237]} rotation={[0, 0, -0.663]}>
                        <mesh geometry={nodes['25A3001-05-1_-_Part'].geometry} material={materials['color-2']} />
                        <mesh geometry={nodes['25A3001-05-1_-_Part_2'].geometry} material={materials['black spray paint-2']} />
                    </group>
                    <mesh geometry={nodes['25A2002-01-1_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0, -0.219]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2002-01-2_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0, -0.143]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2002-02-1_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0.069, -0.181]} />
                    <mesh geometry={nodes['25A2002-03-1_-_Part'].geometry} material={materials['polished steel']} position={[0.095, 0.012, -0.181]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-5_-_Part'].geometry} material={materials.color} position={[-0.004, 0.063, -0.215]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-6_-_Part'].geometry} material={materials.color} position={[0.016, 0.063, -0.215]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-7_-_Part'].geometry} material={materials.color} position={[0.036, 0.063, -0.215]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-8_-_Part'].geometry} material={materials.color} position={[-0.053, 0.006, -0.147]} rotation={[-Math.PI, 0, -0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-9_-_Part'].geometry} material={materials.color} position={[-0.074, 0.006, -0.147]} rotation={[-Math.PI, 0, -0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-11_-_Part'].geometry} material={materials.color} position={[0.084, 0.006, -0.147]} rotation={[-Math.PI, 0, -0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-10_-_Part'].geometry} material={materials.color} position={[0.106, 0.006, -0.147]} rotation={[-Math.PI, 0, -0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-22_-_Part'].geometry} material={materials.color} position={[0.036, 0.063, -0.147]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['25A2002-03-2_-_Part'].geometry} material={materials['polished steel']} position={[-0.063, 0.012, -0.181]} rotation={[-Math.PI, 0, -Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-12_-_Part'].geometry} material={materials.color} position={[0.084, 0.006, -0.215]} rotation={[0, 0, 0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-16_-_Part'].geometry} material={materials.color} position={[-0.004, 0.063, -0.147]} rotation={[-Math.PI, 0, -Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-17_-_Part'].geometry} material={materials.color} position={[0.016, 0.063, -0.147]} rotation={[-Math.PI, 0, -Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-19_-_Part'].geometry} material={materials.color} position={[-0.053, 0.006, -0.215]} rotation={[0, 0, 0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-20_-_Part'].geometry} material={materials.color} position={[-0.074, 0.006, -0.215]} rotation={[0, 0, 0.393]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-21_-_Part'].geometry} material={materials.color} position={[0.106, 0.006, -0.215]} rotation={[0, 0, 0.393]} />
                    <mesh geometry={nodes['25A3001-03-1_-_Part'].geometry} material={materials['color-2']} position={[0.046, -0.003, -0.151]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A2002-04-1_-_Part'].geometry} material={materials['matte steel']} position={[0.016, 0.027, -0.178]} rotation={[0, 0, -0.663]} />
                    <mesh geometry={nodes['25A2002-05-1_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0.027, -0.164]} rotation={[Math.PI / 2, -1.071, -Math.PI / 2]} />
                    <mesh geometry={nodes['25A2002-06-1_-_Part'].geometry} material={materials['polished steel']} position={[0.025, 0.024, -0.168]} rotation={[0, 0, -2.642]} />
                    <mesh geometry={nodes['25A2002-06-2_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.021, -0.188]} rotation={[0, 0, -2.642]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_-_Part'].geometry} material={materials.color} position={[0.028, 0.015, -0.157]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_-_Part'].geometry} material={materials.color} position={[0.028, 0.039, -0.157]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_-_Part'].geometry} material={materials.color} position={[0.003, 0.015, -0.157]} rotation={[0, 0, -1.19]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_-_Part'].geometry} material={materials.color} position={[0.016, 0.027, -0.157]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_-_Part'].geometry} material={materials.color} position={[0.003, 0.039, -0.157]} rotation={[0, 0, -1.19]} />
                    <group position={[-0.004, 0.072, -0.19]}>
                        <mesh geometry={nodes['Revolve1_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_-_Part'].geometry} material={materials.color} />
                    </group>
                    <group position={[-0.004, 0.072, -0.166]}>
                        <mesh geometry={nodes['Revolve1_2_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_2_-_Part'].geometry} material={materials.color} />
                    </group>
                    <group position={[0.036, 0.072, -0.166]} rotation={[0, -0.29, 0]}>
                        <mesh geometry={nodes['Revolve1_3_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_3_-_Part'].geometry} material={materials.color} />
                    </group>
                    <group position={[0.036, 0.072, -0.19]} rotation={[0, -0.29, 0]}>
                        <mesh geometry={nodes['Revolve1_4_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_4_-_Part'].geometry} material={materials.color} />
                    </group>
                    <mesh geometry={nodes['M4_Split_Washer-2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.049, -0.19]} rotation={[-Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['M4_Split_Washer-3_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.049, -0.166]} rotation={[-Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['M4_Split_Washer-5_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.049, -0.19]} rotation={[-Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['M4_Split_Washer-6_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.049, -0.166]} rotation={[-Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['M4_Split_Washer-8_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.07, -0.19]} rotation={[Math.PI / 2, 0, 0.579]} />
                    <mesh geometry={nodes['M4_Split_Washer-9_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.07, -0.19]} rotation={[Math.PI / 2, 0, 0.579]} />
                    <mesh geometry={nodes['M4_Split_Washer-10_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.07, -0.166]} rotation={[Math.PI / 2, 0, 0.579]} />
                    <mesh geometry={nodes['M4_Split_Washer-11_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.07, -0.166]} rotation={[Math.PI / 2, 0, 0.579]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.064, -0.19]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-3_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.064, -0.166]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-4_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.064, -0.19]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-5_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.064, -0.166]} rotation={[Math.PI / 2, 0, 0]} />
                    <group position={[0.019, 0.051, -0.223]} rotation={[Math.PI / 2, -0.663, 0]}>
                        <mesh geometry={nodes['Revolve1_5_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_5_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[0.038, 0.036, -0.223]} rotation={[Math.PI / 2, -0.663, 0]}>
                        <mesh geometry={nodes['Revolve1_6_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_6_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[0.012, 0.003, -0.223]} rotation={[Math.PI / 2, -0.663, 0]}>
                        <mesh geometry={nodes['Revolve1_7_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_7_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[-0.003, 0.042, -0.223]} rotation={[Math.PI / 2, -0.663, 0]}>
                        <mesh geometry={nodes['Revolve1_8_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_8_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[-0.006, 0.018, -0.223]} rotation={[Math.PI / 2, -0.663, 0]}>
                        <mesh geometry={nodes['Revolve1_9_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_9_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[0.034, 0.012, -0.223]} rotation={[Math.PI / 2, -0.663, 0]}>
                        <mesh geometry={nodes['Revolve1_10_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_10_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <mesh geometry={nodes['M5_Split_Washer-2_-_Part'].geometry} material={materials['polished steel']} position={[0.038, 0.036, -0.24]} rotation={[0, 0, -0.673]} />
                    <mesh geometry={nodes['M5_Split_Washer-3_-_Part'].geometry} material={materials['polished steel']} position={[0.034, 0.012, -0.24]} rotation={[0, 0, -0.673]} />
                    <mesh geometry={nodes['M5_Split_Washer-4_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.051, -0.24]} rotation={[0, 0, -0.673]} />
                    <mesh geometry={nodes['M5_Split_Washer-5_-_Part'].geometry} material={materials['polished steel']} position={[-0.003, 0.042, -0.24]} rotation={[0, 0, -0.673]} />
                    <mesh geometry={nodes['M5_Split_Washer-6_-_Part'].geometry} material={materials['polished steel']} position={[-0.006, 0.018, -0.24]} rotation={[0, 0, -0.673]} />
                    <mesh geometry={nodes['M5_Split_Washer-7_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.003, -0.24]} rotation={[0, 0, -0.673]} />
                    <mesh geometry={nodes['M5_Split_Washer-8_-_Part'].geometry} material={materials['polished steel']} position={[0.038, 0.036, -0.226]} rotation={[Math.PI, 0, -2.19]} />
                    <mesh geometry={nodes['M5_Split_Washer-9_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.051, -0.226]} rotation={[Math.PI, 0, -2.19]} />
                    <mesh geometry={nodes['M5_Split_Washer-10_-_Part'].geometry} material={materials['polished steel']} position={[0.034, 0.012, -0.226]} rotation={[Math.PI, 0, -2.19]} />
                    <mesh geometry={nodes['M5_Split_Washer-11_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.003, -0.226]} rotation={[Math.PI, 0, -2.19]} />
                    <mesh geometry={nodes['M5_Split_Washer-12_-_Part'].geometry} material={materials['polished steel']} position={[-0.003, 0.042, -0.226]} rotation={[Math.PI, 0, -2.19]} />
                    <mesh geometry={nodes['M5_Split_Washer-13_-_Part'].geometry} material={materials['polished steel']} position={[-0.006, 0.018, -0.226]} rotation={[Math.PI, 0, -2.19]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-3_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.051, -0.23]} rotation={[Math.PI, 0, 0.269]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-4_-_Part'].geometry} material={materials['polished steel']} position={[0.038, 0.036, -0.23]} rotation={[Math.PI, 0, 0.269]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-5_-_Part'].geometry} material={materials['polished steel']} position={[0.034, 0.012, -0.23]} rotation={[Math.PI, 0, 0.269]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-6_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.003, -0.23]} rotation={[Math.PI, 0, 0.269]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-7_-_Part'].geometry} material={materials['polished steel']} position={[-0.006, 0.018, -0.23]} rotation={[Math.PI, 0, 0.269]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-8_-_Part'].geometry} material={materials['polished steel']} position={[-0.003, 0.042, -0.23]} rotation={[Math.PI, 0, 0.269]} />
                    <mesh geometry={nodes['4X6_Grub_Screw-1_-_Part'].geometry} material={materials.color} position={[0.021, 0.017, -0.185]} rotation={[Math.PI / 2, 0.5, 1.568]} />
                    <mesh geometry={nodes['4X6_Grub_Screw-2_-_Part'].geometry} material={materials.color} position={[0.021, 0.017, -0.171]} rotation={[Math.PI / 2, 0.5, 1.568]} />
                    <mesh geometry={nodes['25A2004-01-2_-_Part'].geometry} material={materials['polished steel']} position={[-0.243, 0.021, 0]} />
                    <mesh geometry={nodes['25A2004-02-1_-_Part'].geometry} material={materials['polished steel']} position={[-0.243, 0.008, 0.226]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-5_-_Part'].geometry} material={materials['polished steel']} position={[-0.243, 0.008, 0.104]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-6_-_Part'].geometry} material={materials['polished steel']} position={[-0.243, 0.008, -0.104]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2004-02-4_-_Part'].geometry} material={materials['polished steel']} position={[-0.243, 0.008, -0.226]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2004-01-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.274, 0.021, 0]} />
                    <mesh geometry={nodes['25A2004-02-1_2_-_Part'].geometry} material={materials['polished steel']} position={[0.274, 0.008, 0.226]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-5_2_-_Part'].geometry} material={materials['polished steel']} position={[0.274, 0.008, 0.104]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-6_2_-_Part'].geometry} material={materials['polished steel']} position={[0.274, 0.008, -0.104]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2004-02-4_2_-_Part'].geometry} material={materials['polished steel']} position={[0.274, 0.008, -0.226]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2005-01-1_-_Part'].geometry} material={materials['polished steel']} position={[-0.114, 0.021, 0]} />
                    <mesh geometry={nodes['25A2004-02-1_3_-_Part'].geometry} material={materials['polished steel']} position={[-0.114, 0.008, 0.213]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-2_-_Part'].geometry} material={materials['polished steel']} position={[-0.114, 0.008, 0.093]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-3_-_Part'].geometry} material={materials['polished steel']} position={[-0.114, 0.008, -0.093]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2004-02-4_3_-_Part'].geometry} material={materials['polished steel']} position={[-0.114, 0.008, -0.213]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2005-01-1_2_-_Part'].geometry} material={materials['polished steel']} position={[0.146, 0.021, 0]} />
                    <mesh geometry={nodes['25A2004-02-1_4_-_Part'].geometry} material={materials['polished steel']} position={[0.146, 0.008, 0.213]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.146, 0.008, 0.093]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2004-02-3_2_-_Part'].geometry} material={materials['polished steel']} position={[0.146, 0.008, -0.093]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2004-02-4_4_-_Part'].geometry} material={materials['polished steel']} position={[0.146, 0.008, -0.213]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2006-01-1_-_Part'].geometry} material={materials['polished steel']} position={[-0.282, 0.002, 0]} />
                    <mesh geometry={nodes['25A3005-02-1_-_Part'].geometry} material={materials['black spray paint-3']} position={[-0.299, -0.011, 0]} rotation={[-Math.PI, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2001-07-1_-_Part'].geometry} material={materials['black medium gloss plastic']} position={[0.001, 0.124, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A1008-01-1_-_Part'].geometry} material={materials.color} position={[0.017, 0.134, 0.218]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-1_-_Part'].geometry} material={materials.color} position={[-0.233, 0.124, 0.228]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-1_-_Part'].geometry} material={materials['color-9']} position={[-0.233, 0.134, 0.225]} rotation={[Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_2_-_Part'].geometry} material={materials.color} position={[-0.233, 0.134, 0.231]} rotation={[Math.PI, 0, -2.882]} />
                    <mesh geometry={nodes['25A1008-02-2_-_Part'].geometry} material={materials.color} position={[0.017, 0.124, 0.228]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-3_-_Part'].geometry} material={materials.color} position={[0.267, 0.124, 0.228]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-2_-_Part'].geometry} material={materials['color-9']} position={[0.017, 0.134, 0.225]} rotation={[Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-3_-_Part'].geometry} material={materials['color-9']} position={[0.267, 0.134, 0.225]} rotation={[Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_2_-_Part'].geometry} material={materials.color} position={[0.017, 0.134, 0.231]} rotation={[Math.PI, 0, -2.882]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_2_-_Part'].geometry} material={materials.color} position={[0.267, 0.134, 0.231]} rotation={[Math.PI, 0, -2.882]} />
                    <mesh geometry={nodes['25A1008-02-4_-_Part'].geometry} material={materials.color} position={[-0.233, 0.124, 0.208]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-5_-_Part'].geometry} material={materials.color} position={[0.017, 0.124, 0.208]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-6_-_Part'].geometry} material={materials.color} position={[0.267, 0.124, 0.208]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-4_-_Part'].geometry} material={materials['color-9']} position={[-0.233, 0.134, 0.213]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-5_-_Part'].geometry} material={materials['color-9']} position={[0.017, 0.134, 0.213]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-6_-_Part'].geometry} material={materials['color-9']} position={[0.267, 0.134, 0.213]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_2_-_Part'].geometry} material={materials.color} position={[-0.233, 0.134, 0.205]} rotation={[0, 0, -0.259]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-5_-_Part'].geometry} material={materials.color} position={[0.267, 0.134, 0.205]} rotation={[0, 0, -0.259]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_2_-_Part'].geometry} material={materials.color} position={[0.017, 0.134, 0.205]} rotation={[0, 0, -0.259]} />
                    <mesh geometry={nodes['LED_Elbow-1-1_-_Part'].geometry} material={materials['color-2']} position={[-0.35, 0.124, -0.194]} rotation={[Math.PI, -Math.PI / 4, Math.PI]} />
                    <mesh geometry={nodes['LED_Elbow-1-2_-_Part'].geometry} material={materials['color-2']} position={[-0.371, 0.124, 0.144]} rotation={[0, -Math.PI / 2, 0]} />
                    <group position={[-0.001, -0.005, 0.151]} rotation={[-Math.PI, 0, 2.479]}>
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part'].geometry} material={materials['matte silver']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_2'].geometry} material={materials['white high gloss plastic']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_3'].geometry} material={materials['white high gloss plastic-2']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_4'].geometry} material={materials['matte silver']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_5'].geometry} material={materials['brushed aluminum']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_6'].geometry} material={materials['chromium plate']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_7'].geometry} material={materials['white high gloss plastic-3']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_8'].geometry} material={materials['white high gloss plastic-4']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_9'].geometry} material={materials['white high gloss plastic-5']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_10'].geometry} material={materials['chromium plate']} />
                        <mesh geometry={nodes['PG457_DC_Motor-2_2_-_Part_11'].geometry} material={materials['white high gloss plastic-6']} />
                    </group>
                    <group position={[0.016, 0.027, 0.237]} rotation={[-Math.PI, 0, 2.479]}>
                        <mesh geometry={nodes['25A3001-05-1_2_-_Part'].geometry} material={materials['color-2']} />
                        <mesh geometry={nodes['25A3001-05-1_2_-_Part_2'].geometry} material={materials['black spray paint-2']} />
                    </group>
                    <mesh geometry={nodes['25A2002-01-1_2_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0, 0.219]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes['25A2002-01-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0, 0.143]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['25A2002-02-1_2_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0.069, 0.181]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['25A2002-03-1_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.063, 0.012, 0.181]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-5_2_-_Part'].geometry} material={materials.color} position={[0.036, 0.063, 0.215]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-6_2_-_Part'].geometry} material={materials.color} position={[0.016, 0.063, 0.215]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-7_2_-_Part'].geometry} material={materials.color} position={[-0.004, 0.063, 0.215]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-8_2_-_Part'].geometry} material={materials.color} position={[0.084, 0.006, 0.147]} rotation={[0, 0, 2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-9_2_-_Part'].geometry} material={materials.color} position={[0.106, 0.006, 0.147]} rotation={[0, 0, 2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-11_2_-_Part'].geometry} material={materials.color} position={[-0.053, 0.006, 0.147]} rotation={[0, 0, 2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-10_2_-_Part'].geometry} material={materials.color} position={[-0.074, 0.006, 0.147]} rotation={[0, 0, 2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-22_2_-_Part'].geometry} material={materials.color} position={[-0.004, 0.063, 0.147]} />
                    <mesh geometry={nodes['25A2002-03-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.095, 0.012, 0.181]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-12_2_-_Part'].geometry} material={materials.color} position={[-0.053, 0.006, 0.215]} rotation={[-Math.PI, 0, -2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-16_2_-_Part'].geometry} material={materials.color} position={[0.036, 0.063, 0.147]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-17_2_-_Part'].geometry} material={materials.color} position={[0.016, 0.063, 0.147]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-19_2_-_Part'].geometry} material={materials.color} position={[0.084, 0.006, 0.215]} rotation={[-Math.PI, 0, -2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-20_2_-_Part'].geometry} material={materials.color} position={[0.106, 0.006, 0.215]} rotation={[-Math.PI, 0, -2.748]} />
                    <mesh geometry={nodes['4X12_18-8_Stainless_Steel_Socket_Head_Screws-21_2_-_Part'].geometry} material={materials.color} position={[-0.074, 0.006, 0.215]} rotation={[-Math.PI, 0, -2.748]} />
                    <mesh geometry={nodes['25A3001-03-1_2_-_Part'].geometry} material={materials['color-2']} position={[-0.014, -0.003, 0.151]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A2002-04-1_2_-_Part'].geometry} material={materials['matte steel']} position={[0.016, 0.027, 0.178]} rotation={[-Math.PI, 0, 2.479]} />
                    <mesh geometry={nodes['25A2002-05-1_2_-_Part'].geometry} material={materials['polished steel']} position={[0.016, 0.027, 0.164]} rotation={[Math.PI / 2, 1.071, Math.PI / 2]} />
                    <mesh geometry={nodes['25A2002-06-1_2_-_Part'].geometry} material={materials['polished steel']} position={[0.006, 0.024, 0.168]} rotation={[Math.PI, 0, 0.5]} />
                    <mesh geometry={nodes['25A2002-06-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.021, 0.188]} rotation={[Math.PI, 0, 0.5]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_3_-_Part'].geometry} material={materials.color} position={[0.003, 0.015, 0.157]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_3_-_Part'].geometry} material={materials.color} position={[0.003, 0.039, 0.157]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_3_-_Part'].geometry} material={materials.color} position={[0.028, 0.015, 0.157]} rotation={[-Math.PI, 0, 1.952]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_3_-_Part'].geometry} material={materials.color} position={[0.016, 0.027, 0.157]} rotation={[-Math.PI, 0, Math.PI]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_3_-_Part'].geometry} material={materials.color} position={[0.028, 0.039, 0.157]} rotation={[-Math.PI, 0, 1.952]} />
                    <group position={[0.036, 0.072, 0.19]} rotation={[-Math.PI, 0, Math.PI]}>
                        <mesh geometry={nodes['Revolve1_11_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_11_-_Part'].geometry} material={materials.color} />
                    </group>
                    <group position={[0.036, 0.072, 0.166]} rotation={[-Math.PI, 0, Math.PI]}>
                        <mesh geometry={nodes['Revolve1_12_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_12_-_Part'].geometry} material={materials.color} />
                    </group>
                    <group position={[-0.004, 0.072, 0.166]} rotation={[-Math.PI, 0.29, Math.PI]}>
                        <mesh geometry={nodes['Revolve1_13_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_13_-_Part'].geometry} material={materials.color} />
                    </group>
                    <group position={[-0.004, 0.072, 0.19]} rotation={[-Math.PI, 0.29, Math.PI]}>
                        <mesh geometry={nodes['Revolve1_14_-_Part'].geometry} material={materials.color} />
                        <mesh geometry={nodes['Combine1_14_-_Part'].geometry} material={materials.color} />
                    </group>
                    <mesh geometry={nodes['M4_Split_Washer-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.049, 0.19]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes['M4_Split_Washer-3_2_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.049, 0.166]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes['M4_Split_Washer-5_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.049, 0.19]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes['M4_Split_Washer-6_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.049, 0.166]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes['M4_Split_Washer-8_2_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.07, 0.19]} rotation={[Math.PI / 2, 0, -2.563]} />
                    <mesh geometry={nodes['M4_Split_Washer-9_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.07, 0.19]} rotation={[Math.PI / 2, 0, -2.563]} />
                    <mesh geometry={nodes['M4_Split_Washer-10_2_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.07, 0.166]} rotation={[Math.PI / 2, 0, -2.563]} />
                    <mesh geometry={nodes['M4_Split_Washer-11_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.07, 0.166]} rotation={[Math.PI / 2, 0, -2.563]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-2_2_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.064, 0.19]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-3_2_-_Part'].geometry} material={materials['polished steel']} position={[0.036, 0.064, 0.166]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-4_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.064, 0.19]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <mesh geometry={nodes['4X30_Button_Head_Hex_Drive_Screw-5_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.004, 0.064, 0.166]} rotation={[Math.PI / 2, 0, -Math.PI]} />
                    <group position={[0.012, 0.051, 0.223]} rotation={[Math.PI / 2, 0.663, -Math.PI]}>
                        <mesh geometry={nodes['Revolve1_15_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_15_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[-0.006, 0.036, 0.223]} rotation={[Math.PI / 2, 0.663, -Math.PI]}>
                        <mesh geometry={nodes['Revolve1_16_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_16_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[0.019, 0.003, 0.223]} rotation={[Math.PI / 2, 0.663, -Math.PI]}>
                        <mesh geometry={nodes['Revolve1_17_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_17_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[0.034, 0.042, 0.223]} rotation={[Math.PI / 2, 0.663, -Math.PI]}>
                        <mesh geometry={nodes['Revolve1_18_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_18_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[0.038, 0.018, 0.223]} rotation={[Math.PI / 2, 0.663, -Math.PI]}>
                        <mesh geometry={nodes['Revolve1_19_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_19_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <group position={[-0.003, 0.012, 0.223]} rotation={[Math.PI / 2, 0.663, -Math.PI]}>
                        <mesh geometry={nodes['Revolve1_20_-_Part'].geometry} material={materials['polished steel']} />
                        <mesh geometry={nodes['Combine1_20_-_Part'].geometry} material={materials['polished steel']} />
                    </group>
                    <mesh geometry={nodes['M5_Split_Washer-2_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.006, 0.036, 0.24]} rotation={[-Math.PI, 0, 2.469]} />
                    <mesh geometry={nodes['M5_Split_Washer-3_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.003, 0.012, 0.24]} rotation={[-Math.PI, 0, 2.469]} />
                    <mesh geometry={nodes['M5_Split_Washer-4_2_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.051, 0.24]} rotation={[-Math.PI, 0, 2.469]} />
                    <mesh geometry={nodes['M5_Split_Washer-5_2_-_Part'].geometry} material={materials['polished steel']} position={[0.034, 0.042, 0.24]} rotation={[-Math.PI, 0, 2.469]} />
                    <mesh geometry={nodes['M5_Split_Washer-6_2_-_Part'].geometry} material={materials['polished steel']} position={[0.038, 0.018, 0.24]} rotation={[-Math.PI, 0, 2.469]} />
                    <mesh geometry={nodes['M5_Split_Washer-7_2_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.003, 0.24]} rotation={[-Math.PI, 0, 2.469]} />
                    <mesh geometry={nodes['M5_Split_Washer-8_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.006, 0.036, 0.226]} rotation={[0, 0, 0.951]} />
                    <mesh geometry={nodes['M5_Split_Washer-9_2_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.051, 0.226]} rotation={[0, 0, 0.951]} />
                    <mesh geometry={nodes['M5_Split_Washer-10_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.003, 0.012, 0.226]} rotation={[0, 0, 0.951]} />
                    <mesh geometry={nodes['M5_Split_Washer-11_2_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.003, 0.226]} rotation={[0, 0, 0.951]} />
                    <mesh geometry={nodes['M5_Split_Washer-12_2_-_Part'].geometry} material={materials['polished steel']} position={[0.034, 0.042, 0.226]} rotation={[0, 0, 0.951]} />
                    <mesh geometry={nodes['M5_Split_Washer-13_2_-_Part'].geometry} material={materials['polished steel']} position={[0.038, 0.018, 0.226]} rotation={[0, 0, 0.951]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-3_2_-_Part'].geometry} material={materials['polished steel']} position={[0.012, 0.051, 0.23]} rotation={[0, 0, -2.872]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-4_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.006, 0.036, 0.23]} rotation={[0, 0, -2.872]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-5_2_-_Part'].geometry} material={materials['polished steel']} position={[-0.003, 0.012, 0.23]} rotation={[0, 0, -2.872]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-6_2_-_Part'].geometry} material={materials['polished steel']} position={[0.019, 0.003, 0.23]} rotation={[0, 0, -2.872]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-7_2_-_Part'].geometry} material={materials['polished steel']} position={[0.038, 0.018, 0.23]} rotation={[0, 0, -2.872]} />
                    <mesh geometry={nodes['5X20_Button_Head_Hex_Drive_Screw-8_2_-_Part'].geometry} material={materials['polished steel']} position={[0.034, 0.042, 0.23]} rotation={[0, 0, -2.872]} />
                    <mesh geometry={nodes['4X6_Grub_Screw-1_2_-_Part'].geometry} material={materials.color} position={[0.01, 0.017, 0.185]} rotation={[Math.PI / 2, -0.5, -1.574]} />
                    <mesh geometry={nodes['4X6_Grub_Screw-2_2_-_Part'].geometry} material={materials.color} position={[0.01, 0.017, 0.171]} rotation={[Math.PI / 2, -0.5, -1.574]} />
                    <mesh geometry={nodes['25A1008-01-1_2_-_Part'].geometry} material={materials.color} position={[0.017, 0.134, -0.218]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-1_2_-_Part'].geometry} material={materials.color} position={[-0.233, 0.124, -0.208]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-1_2_-_Part'].geometry} material={materials['color-9']} position={[-0.233, 0.134, -0.211]} rotation={[Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-1_4_-_Part'].geometry} material={materials.color} position={[-0.233, 0.134, -0.205]} rotation={[Math.PI, 0, -2.882]} />
                    <mesh geometry={nodes['25A1008-02-2_2_-_Part'].geometry} material={materials.color} position={[0.017, 0.124, -0.208]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-3_2_-_Part'].geometry} material={materials.color} position={[0.267, 0.124, -0.208]} rotation={[0, -Math.PI / 2, 0]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-2_2_-_Part'].geometry} material={materials['color-9']} position={[0.017, 0.134, -0.211]} rotation={[Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-3_2_-_Part'].geometry} material={materials['color-9']} position={[0.267, 0.134, -0.211]} rotation={[Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-2_4_-_Part'].geometry} material={materials.color} position={[0.017, 0.134, -0.205]} rotation={[Math.PI, 0, -2.882]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-3_4_-_Part'].geometry} material={materials.color} position={[0.267, 0.134, -0.205]} rotation={[Math.PI, 0, -2.882]} />
                    <mesh geometry={nodes['25A1008-02-4_2_-_Part'].geometry} material={materials.color} position={[-0.233, 0.124, -0.228]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-5_2_-_Part'].geometry} material={materials.color} position={[0.017, 0.124, -0.228]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['25A1008-02-6_2_-_Part'].geometry} material={materials.color} position={[0.267, 0.124, -0.228]} rotation={[0, Math.PI / 2, 0]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-4_2_-_Part'].geometry} material={materials['color-9']} position={[-0.233, 0.134, -0.223]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-5_2_-_Part'].geometry} material={materials['color-9']} position={[0.017, 0.134, -0.223]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['M4_T_slot_nut_-_2020-6_2_-_Part'].geometry} material={materials['color-9']} position={[0.267, 0.134, -0.223]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-4_4_-_Part'].geometry} material={materials.color} position={[-0.233, 0.134, -0.231]} rotation={[0, 0, -0.259]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-5_2_-_Part'].geometry} material={materials.color} position={[0.267, 0.134, -0.231]} rotation={[0, 0, -0.259]} />
                    <mesh geometry={nodes['4X8_18-8_Stainless_Steel_Socket_Head_Screws-6_4_-_Part'].geometry} material={materials.color} position={[0.017, 0.134, -0.231]} rotation={[0, 0, -0.259]} />
                </group>
                <perspectiveCamera far={100} near={0.01} fov={18.423} position={[-1.576, 0.911, 0.712]} rotation={[-0.875, -0.956, -0.774]} />
                <perspectiveCamera far={100} near={0.01} fov={15} position={[4.445, 1.982, 4.445]} rotation={[-0.322, 0.759, 0.226]} />
                <directionalLight intensity={0.577} color="#c8c8c8" position={[5.521, 8.271, 1.053]} rotation={[-1.444, 0.585, 1.344]} />
                <directionalLight intensity={0.577} color="#c8c8c8" position={[1.163, 4.81, 8.69]} rotation={[-0.506, 0.117, 0.064]} />
            </group>
        </group>
    )
}

useGLTF.preload('/AGV.glb')
